### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by joaochris** [Stanley80-Peng/VirtualMonitor#1]
Hi! Can you help me how do I install?

**Comment by Stanley80-Peng** [comment]
I'm sorry that you can't install the virtual monitor because it is made specially for a lab in the field of AI, I will soon launch a version that everyone can use.


| |
Stanley Peng
|
|
***@***.***
|
签名由网易邮箱大师定制
On 3/19/2021 ***@***.***> wrote：

Hi! Can you help me how do I install?

**Comment by joaochris** [comment]
Okay :D
